version: '3'

services:
  api:
    depends_on:
      - mongodb
    container_name: myapp
    restart: always
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 7024:7024
    stdin_open: true
    tty: true



  mongodb:
    container_name: mymongodb
    # nome da imagem a ir buscar ao docker hub
    image: mongo
    #build: ./mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

volumes:
  db:

networks:
  default:
    driver: bridge